# Generated by Django 5.0.7 on 2024-07-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_professor',
            field=models.BooleanField(default=False, help_text='Designates whether the user is a professor.', verbose_name='student staus'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False, help_text='Designates whether the user is a student.', verbose_name='student staus'),
            preserve_default=False,
        ),
    ]
